[[GAP_pkg_profiling]]
arch = "aarch64"
git-tree-sha1 = "5a63279b557b8ec417476e7bf3e1ae59b663cc39"
os = "macos"

    [[GAP_pkg_profiling.download]]
    sha256 = "f272d96a23e562bb1e35b6752659513719f838f1df2a10e54994a046640b72e7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+1/GAP_pkg_profiling.v200.600.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_profiling]]
arch = "aarch64"
git-tree-sha1 = "5993d0933d8782cea8c3b6a61ea31146e0c5f53c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "86d7244d01980e53ebcf63407440854ce59303d72c66cff06d1ba90ff94ee399"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+1/GAP_pkg_profiling.v200.600.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_profiling]]
arch = "aarch64"
git-tree-sha1 = "d78cf55dc1ef0661655df27e5b0a219ec868cfbd"
libc = "musl"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "8cf1e1dcc045d7cedaeb5386556605cc3411050ccefeec80fab76f5d2dc0691b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+1/GAP_pkg_profiling.v200.600.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_profiling]]
arch = "powerpc64le"
git-tree-sha1 = "b977aeb873885963a977012ae173225fa86268ba"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "f9817bd385b50ede4381a272bba97d86e32f3a7778390c5573ed3eaa9e72aade"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+1/GAP_pkg_profiling.v200.600.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "a07df54f16f4e01601c176de47b24d5d2bb9c0b0"
os = "macos"

    [[GAP_pkg_profiling.download]]
    sha256 = "cff298ec1bddd7eddba6e50322b158f37e215e25b526b15ccbfa8fe0869a2eb1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+1/GAP_pkg_profiling.v200.600.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "1f47f63161aeab2e015927aed6340b843a1d6a1a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "fe0d80f22f1853ca919f4021b4dccaf09c5bbaf0dc2ed6767029a58637506cc0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+1/GAP_pkg_profiling.v200.600.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "05a56a8cd49dc659cad9ed313428e6d4d1e3b8a2"
libc = "musl"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "51abcf73aae96140d10781a56785d03765f9e711b8c84ec9dbeaec9fd251969f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+1/GAP_pkg_profiling.v200.600.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "b0df38a77ea5493ab9ad50984d4d28d8ad11d193"
os = "freebsd"

    [[GAP_pkg_profiling.download]]
    sha256 = "40d6f826fe9f98d9883736081e7b95d345f4ad18ce562d6b211cbc57b7840f73"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+1/GAP_pkg_profiling.v200.600.0.x86_64-unknown-freebsd.tar.gz"
