[[GAP_pkg_profiling]]
arch = "aarch64"
git-tree-sha1 = "4e2a8a5fd66356cf9ba72ab5c5ab46aca28efdbe"
os = "macos"

    [[GAP_pkg_profiling.download]]
    sha256 = "b8ec59080e3ca717b6b6d57b1c9d3e86d53b2d023b39e550765c3226aaa9f03f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+0/GAP_pkg_profiling.v200.600.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_profiling]]
arch = "aarch64"
git-tree-sha1 = "6bed684ec9f50b24ce0fc9fabc31d7365dfb630a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "e1201663c4a676aab3803d5fead70f9c6aea0e9ac273b4bf448237392025e292"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+0/GAP_pkg_profiling.v200.600.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_profiling]]
arch = "aarch64"
git-tree-sha1 = "22baed280bd1a7691d3f377bce521287af3c47cb"
libc = "musl"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "e288569e4fced260a0ed89b680b765a990daa306b45b5a7cd81a98ac5775282d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+0/GAP_pkg_profiling.v200.600.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_profiling]]
arch = "powerpc64le"
git-tree-sha1 = "36c086e0d89a2541c400c24ec33fff4265bbf966"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "302d25eb7c82ab7381927905b060ec9bc142380f9de12784bd83b7f8898d555a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+0/GAP_pkg_profiling.v200.600.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "9b09d4c4a12364d8f5a7ec2ec9b9c2f7e48b879d"
os = "macos"

    [[GAP_pkg_profiling.download]]
    sha256 = "c2d22ec3a50fc396875625ee3ea65bf34729ee91ec5eef3a071f2d55f7dab959"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+0/GAP_pkg_profiling.v200.600.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "523b363534649e92f1afe3a3da2c5b179ca2a26a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "dc35bcd2d887daddfd48d4b74a04c7f6948b4fc43d3f82c2d022a3acab905847"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+0/GAP_pkg_profiling.v200.600.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "578f3b18a25886954c0379cebbf59791ff116cd6"
libc = "musl"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "2d68fd2d4912c7e1bd411a2da91f41959465eebcdac4233df9621ad29492d722"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+0/GAP_pkg_profiling.v200.600.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "cfee3187dc7564e8904a14f4d9957b0b56b02cbc"
os = "freebsd"

    [[GAP_pkg_profiling.download]]
    sha256 = "5854d5f6d6a95a53e78a3d5599873fe02ea95bf7239dd9e289fe9e2211ca3d97"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v200.600.0+0/GAP_pkg_profiling.v200.600.0.x86_64-unknown-freebsd.tar.gz"
