[[GAP_pkg_profiling]]
arch = "aarch64"
git-tree-sha1 = "c987c2b8bb828d0bae07fb51ee667fcff98d0ff2"
os = "macos"

    [[GAP_pkg_profiling.download]]
    sha256 = "46399726dbe93ae459a75c9fafe8dc9998d2ede12e3f862204d6ac2c705cb0a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_profiling]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0583a2869247376035b892d542d4cdcce17d0025"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "e918d3025fcc98d3d290c7522ceca497c24e4f04567f79e498cb0b625c27a87c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_profiling]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aae396cd2bbe15c90250b1f6ff7f971adb8ffa2e"
libc = "musl"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "d4c6c94c042f0ed2a0233922f4f9f79a87ddf6ac54dfbdb591b1239066cb04c1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_profiling]]
arch = "aarch64"
git-tree-sha1 = "02b83c7b1f2b1a4d507958e19e2e75b9b07d009c"
os = "freebsd"

    [[GAP_pkg_profiling.download]]
    sha256 = "00681fae262596ffff32233f2537dff24c640110da6946fddb248d35933bb64f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_profiling]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c80913eec122d30769ccbea0b7c2247972741a5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "5ce55876a06a5b583f8f305c7fa967550a8397ef3af1508720fb76a9f787d43f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_profiling]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18dfc6a309b3532d62e6bb966f2629184a8b08eb"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "59d95a91fee5fecbbd420a6a683fdf7fd6bb7fef14a0eb542aac2995ae2efdfe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.riscv64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "f131a6de698341df6bae88949d8b8df576107de9"
os = "macos"

    [[GAP_pkg_profiling.download]]
    sha256 = "69d4d0f6c0adc5ce6916185b5e43d6e93337192da343bf8d08ad06193b4c2917"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10a25aac7f40ef05e7bf642cff0eac814c48c79c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "831cdf8abe4bbb759fe86ae3fc6bcf15320b4bbd30a3ed78dfea947ede3f8c03"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab201d00fffba274e0ec6bc943431874ce7a71ae"
libc = "musl"
os = "linux"

    [[GAP_pkg_profiling.download]]
    sha256 = "a5fd170616dc19a341bf6dbfbf42b51f5fec2a5e24d5a33d15e45e8c87df1212"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_profiling]]
arch = "x86_64"
git-tree-sha1 = "c9ff2839aeb4ed82778668cea1618efb11ee2ca5"
os = "freebsd"

    [[GAP_pkg_profiling.download]]
    sha256 = "51bd77983aabd759d37497caa2e3fe707b59e46e2dd1e176f70410e9f3256661"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_profiling_jll.jl/releases/download/GAP_pkg_profiling-v201.60200.1+0/GAP_pkg_profiling.v201.60200.1.x86_64-unknown-freebsd.tar.gz"
